Main <- Dev
risc0/demos pull request #12
Opened 2024-02-20 19:53 UTC by hmrtn

Adds zkKYC demo repo

2024-02-22 20:45 UTC, intoverflow requested changes
We're missing the license/copyright notice on several files. Otherwise, looks good. I'll take another pass through this afternoon or tomorrow.

2024-02-22 20:45 UTC, intoverflow commented on zk-kyc/README.md
> +
Needs a disclaimer about the demo being experimental
```suggestion
> WARNING: this project is experimental and should not be used for any production use cases. Use at your own risk.
```

2024-02-22 22:49 UTC, hmrtn commented
@intoverflow I added the standard license header to all the rust files. How should we license the solidity files and react application?

2024-02-22 22:53 UTC, intoverflow commented
> @intoverflow I added the standard license header to all the rust files. How should we license the solidity files and react application?

Let's do them both with Apache 2. Here's an example from the verifier contract:

https://github.com/risc0/risc0/blob/main/bonsai/ethereum/contracts/IRiscZeroVerifier.sol

2024-02-23 19:47 UTC, intoverflow approved these changes
Beautiful 😍

2024-02-23 19:47 UTC, intoverflow commented on zk-kyc/README.md
> +> WARNING: this project is experimental and should not be used for any production use cases. Use at your own risk.
✅

2024-02-23 19:47 UTC, intoverflow commented on zk-kyc/README.md
> +As a sample application, the ERC721 Token Minting Demo is designed for demonstration purposes and is not suitable for production use. It is important to be aware that:
✅

2024-02-23 19:47 UTC, intoverflow commented on zk-kyc/README.md
> +This demo leverages ID.me to generate a client authentication token. The token includes a nonce that is associated with the user's connected wallet address, employing principles from the [OpenPubkey:
```suggestion
This demo leverages [ID.me](https://www.id.me/) to generate a client authentication token. The token includes a nonce that is associated with the user's connected wallet address, employing principles from the [OpenPubkey: Augmenting OpenID Connect with User held Signing Keys](https://eprint.iacr.org/2023/296) paper. The JWT's integrity is then verified within the guest using ID.me's public RS256 signing [certificates](https://api.id.me/oidc/.well-known/jwks). Subsequently, the guest generates a cryptographic proof of the JWT's integrity and issues a receipt. This receipt, containing the SNARK, an obfuscated identifier, and the user's address, can be validated on the onchain for ERC721 token minting or other transactions, if valid.
```

2024-02-23 19:47 UTC, intoverflow commented on zk-kyc/contracts/README.md
> +This directory hosts a Foundry project dedicated to the smart contracts utilized by the demo application. Please note that these contracts are unaudited and are intended solely for demonstration purp
✅

2024-02-23 22:21 UTC, merged